version: "3"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:80
    volumes:
      - .:/var/www/html

  postgres:
    container_name: postgres-web
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgresweb}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
